// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

    int num = Integer.parseInt(args[0]);
    
	int greater = 0;
	int lessOrEqual = 0;
    
	while (num>0) {
		num --;
		double randomNum = (Math.random());
		if (randomNum>0.5) {
        greater ++; 
		}
		else {
		lessOrEqual ++;	
		}
	}

	double ratio = greater/lessOrEqual;
    
	if (greater ==0 || lessOrEqual ==0) 
	{
	System.out.println("> 0.5: "+greater+" times");
	System.out.println("<= 0.5: "+lessOrEqual+" times");
	}
	else {
	System.out.println("> 0.5: "+greater+" times");
	System.out.println("<= 0.5: "+lessOrEqual+" times");
	System.out.println("Ratio: "+ratio);
	     }

	}
}
